### PR TITLE
fix: support diffs that change single line

### PR DESCRIPTION
**Pull request by DaveHarrington**
Single line diffs without context are not currently supported. This means all suggested changes include context, which has two issues:
1. The suggested change is not annotated on the line with the change, but several lines down
2. Changes (rather than additions) which need a suggested change don't work, due to https://github.com/orgs/community/discussions/37821

Fix these issues by setting context to 0, and fix handling of single line changes.

### CODE REVIEW

**Review by atkinsonm — APPROVED** [review]

**Review by parkerbxyz — COMMENTED** [review]
This is looking good, thank you @DaveHarrington! ✨ I refactored a bit to separate concerns and reduce duplication.

In some initial testing with a single-line change, I ran into the following error that I'd like to address here if possible before merging:

> RequestError [HttpError]: Unprocessable Entity: "Pull request review thread start line must precede the end line."

Have you tested the changes on this branch with a single line change?

**Comment by shravanngoswamii** [comment]
I was trying to use this workflow for suggesting latest version if my VERSION file have outdated version. Its single line file.
here is my workflow: https://github.com/shravanngoswamii/docs/blob/master/.github/workflows/vcheck.yml
Am I using it in right way and will this run fine after this PR is merged!

**Comment by parkerbxyz** [comment]
> Single line diffs without context are not currently supported. This means all suggested changes include context, which has two issues:
> 
> 1. The suggested change is not annotated on the line with the change, but several lines down
> 2. Changes (rather than additions) which need a suggested change don't work, due to https://github.com/orgs/community/discussions/37821

@DaveHarrington Can you provide an example of this so I can reproduce it, please?

**Comment by shravanngoswamii** [comment]
Thanks a lot!

**Pull request merged**
